### PR TITLE
Fixed typo in overview.md

### PR DESCRIPTION
**Pull request by icnocop**

### CODE REVIEW

**Comment by huserben** [comment]
Thank you @icnocop

**Comment by icnocop** [comment]
I just noticed this PR was approved but not merged. 🤔

**Comment by huserben** [comment]
Hmm thanks for the info, seems like I accidentally closed without merging (and also deleted the source branch).
I'm trying to update master with your changes manually then. I'll let you know once it's in.

**Comment by huserben** [comment]
As I wasn't able to reopen the PR and merge it I recreated it locally - please quickly check here if everything is correct:
https://github.com/huserben/TfsExtensions/pull/124

**Comment by icnocop** [comment]
PR #124 looks good. Thank you.

**Pull request closed without merging**
